In [1]:
import matplotlib.pyplot as plt
import matplotlib.gridspec as gs
import numpy as np
from grating import *
from ext_signal import *
from scipy.stats import qmc

lum in LMS = [0.45436904 0.47353315 0.0720978 ]
[[1.31265115 0.37916654 0.17658182]
 [0.37916654 0.43588297 0.06613005]
 [0.17658182 0.06613005 1.03101131]]
[[10.82668925 -2.48855249  0.0461736 ]
 [-2.48855249  1.38614356 -0.12768065]
 [ 0.0461736  -0.12768065  1.15767798]]


In [2]:
def acuity(ecc):
    k = 0.2049795945022049
    log_cpd0 = 3.6741080244555278
    cpd = np.exp(-k*ecc + log_cpd0)
    return 1/cpd/4

acuity(0.08)

0.00644787913828977

In [3]:
K_onC = 29.13289963
K_onS = 23.17378917
K_offC = 22.71914498
K_offS = 12.53276353
r_C = (acuity(0.095) + acuity(0))/2
#r_C = 0.0065
r_S = r_C*3
cov = 0.53753
def zeroCross(k1, k2, r1, r2):
    return np.sqrt(np.log(k1/k2)/(r2*r2 - r1*r1))*r1*r2
SF = 1.0/(zeroCross(K_offC, K_onS*cov, r_C, r_S)*2 + zeroCross(K_onC, K_offS*cov, r_C, r_S)*2)
print(SF)

37.07018290634954


In [4]:
# color-drifting
# crest = np.array([0.50650651, 0.27006487, 0.3609756])
# valley = np.array([0.28128128, 0.48617513, 0.3609756])
#crest = np.array([0.393893895, 0.37812, 0.3609756])
#valley = np.array([0.393893895, 0.37812, 0.3609756])
# crest = np.array([0.55, 0.45, 0.5])
# valley = np.array([0.45, 0.55, 0.5])
# crest = np.array([0.9, 0.1, 0.5])
# valley = np.array([0.1, 0.9, 0.5])
# crest = np.array([0.8, 0.2, 0.5])
# valley = np.array([0.2, 0.8, 0.5])
# crest = np.array([0.7, 0.3, 0.5])
# valley = np.array([0.3, 0.7, 0.5])
# crest = np.array([0.6, 0.4, 0.5])
# valley = np.array([0.4, 0.6, 0.5])


inputLMS = True

#range_deg = 0.095 # eccentricity from the origin
range_deg = 0.0344#0.12672379774682216 # eccentricity from the origin
print(acuity(range_deg))
# buffer_deg = acuity(range_deg)*2
buffer_deg = acuity(range_deg)*2
print(f'range_deg = {range_deg}, buffer_deg = {buffer_deg}')
SF = 20
# SF = 10
TF = 8
time = np.array([1/TF])
neye = 1
#path = 'D:/scratch/patchV1/resource/'
#path = 'C:/Users/gueux/Repos/patchV1/Data/'
path = '/root/autodl-tmp/ljy/resource_8/'

0.006387891156464933
range_deg = 0.0344, buffer_deg = 0.012775782312929865


In [5]:
# def sine_wave(amp, radTF, radSF, direction, a, b, c1, c2, control, sharpness, phase, t, X, Y, bar, center, wing):
#     phi = (np.cos(direction)*X + np.sin(direction)*Y)*radSF - radTF*t
#     if bar:
#         #floor_phi = np.floor(phi/(2*np.pi)).astype(int)
#         #phi_tmp = phi-floor_phi*2*np.pi
#         pick = np.abs(phi + (phase + center)) > wing
#         phi[pick] = -phase
#     rel_color = np.reshape(1+amp*np.sin(phi + phase), (a*b,1))/2
#     if sharpness != 1:
#         if sharpness > 0:
#             exp_half = np.exp(sharpness/2)+1
#             A = np.power(exp_half,2)/(np.exp(sharpness)-1)
#             C = exp_half/(1-np.exp(sharpness))
#             rel_color = A/(1.0 + np.exp(-sharpness*(rel_color-0.5))) + C
#         else:
#             rel_color[rel_color > 0.5] = 1
#             rel_color[rel_color < 0.5] = 0
        
#     assert((rel_color <= 1.0).all())
#     assert((rel_color >= 0.0).all())
#     color = np.matmul(np.ones((a*b,1)), c1) + np.matmul(rel_color, (c2-c1))
#     for i in range(3):
#         if control[i] > 0:
#             assert((color[:,i] <= c1[0,i]).all())
#             assert((color[:,i] >= c2[0,i]).all())
#         else:
#             assert((color[:,i] >= c1[0,i]).all())
#             assert((color[:,i] <= c2[0,i]).all())
        
#     return color.reshape((b,a,3))

In [6]:
# crest = np.array([0.9, 0.1, 0.5])
# valley = np.array([0.1, 0.9, 0.5])
# crest = np.array([0.8, 0.2, 0.5])
# valley = np.array([0.2, 0.8, 0.5])
# crest = np.array([0.7, 0.3, 0.5])
# valley = np.array([0.3, 0.7, 0.5])
# crest = np.array([0.6, 0.4, 0.5])
# valley = np.array([0.4, 0.6, 0.5])


In [7]:
# # int random
# center = np.pi/2
# wing = np.pi/2
# sharpness = 1
# C = np.random.randint(1,10,size=1000)
# P = np.random.randint(0,360,size=1000)
# SF = np.random.randint(5,21,size=1000)
# D = np.random.randint(0,18,size=1000)
# for i in range(1000):
#     video_fn = path + f'static_color-random_{i+1}'
#     c = C[i]
#     phase = P[i]
#     sf = SF[i]
#     d = D[i]
#     crest = np.array([0.5+c*0.05, 0.5-c*0.05, 0.5])#LMS
#     valley = np.array([0.5-c*0.05, 0.5+c*0.05, 0.5])
#     orient = d*10
    
#     cfg_fn = path + f'static_color-random_{i+1}_cfg'
#     f = open(cfg_fn+ '.bin', 'wb') # sf,d,p,c
#     np.array([sf]).astype('f4').tofile(f)
#     np.array([orient]).astype('f4').tofile(f)
#     np.array([phase]).astype('f4').tofile(f)
#     np.array([c]).astype('f4').tofile(f)
#     crest.astype('f4').tofile(f)
#     valley.astype('f4').tofile(f)
#     f.close()
    
    
#     generate_grating(1.0, sf, TF, orient, 16, crest, valley, video_fn, time, phase, sharpness, frameRate = 1, ecc = range_deg, buffer_ecc = buffer_deg, gtype='drifting', neye = neye, bar = False, center = center, wing = wing, mask = None, inputLMS = inputLMS,genMovie = True)


    
    
    
    

In [8]:
# C = np.random.uniform(5,20,size=1000)
# C = C.astype('float32')

In [9]:
# C[-1]

In [10]:
# # continue random
# center = np.pi/2
# wing = np.pi/2
# sharpness = 1
# C = np.random.uniform(0.05,0.5,size=10000)
# P = np.random.uniform(0,360,size=10000)
# SF = np.random.uniform(5,21,size=10000)
# D = np.random.uniform(0,180,size=10000)
# C = C.astype('float32')
# P = P.astype('float32')
# SF = SF.astype('float32')
# D = D.astype('float32')
# for i in range(10000):
#     video_fn = path + f'static_color-random_{i+1}'
#     c = C[i]
#     phase = P[i]
#     sf = SF[i]
#     d = D[i]
#     crest = np.array([0.5+c, 0.5-c, 0.5])#LMS
#     valley = np.array([0.5-c, 0.5+c, 0.5])
#     orient = d
    
#     cfg_fn = path + f'static_color-random_{i+1}_cfg'
#     f = open(cfg_fn+ '.bin', 'wb') # sf,d,p,c
#     np.array([sf]).astype('f4').tofile(f)
#     np.array([orient]).astype('f4').tofile(f)
#     np.array([phase]).astype('f4').tofile(f)
#     np.array([c]).astype('f4').tofile(f)
#     crest.astype('f4').tofile(f)
#     valley.astype('f4').tofile(f)
#     f.close()
    
    
#     generate_grating(1.0, sf, TF, orient, 16, crest, valley, video_fn, time, phase, sharpness, frameRate = 1, ecc = range_deg, buffer_ecc = buffer_deg, gtype='drifting', neye = neye, bar = False, center = center, wing = wing, mask = None, inputLMS = inputLMS,genMovie = True)


    
    
    
    

In [11]:
# crest_list = []
# valley_list = []
# # for i in [0.1,0.2,0.3,0.4]:
# for i in [0.1]:
    
#     crest = np.array([0.5+i, 0.5-i, 0.5])#LMS
#     valley = np.array([0.5-i, 0.5+i, 0.5])  
#     crest_list.append(crest)    
#     valley_list.append(valley)


# SF_list = [5, 10, 15, 20]
# SF_list = [20]
# phase_list = np.arange(1,7)
# phase_list = np.arange(1,13)
# iOri_list = np.arange(1,7)


# center = np.pi/2
# wing = np.pi/2
# sharpness = 1
# for iOri in iOri_list:
#     for SF in SF_list:
#         for p in phase_list:
#             for contrast in range(1,len(valley_list)+1):
#                 video_fn = path + f'static_color-SF{SF}-TF{TF}-c{contrast}-p{p}_d{iOri}-pd'  
#                 orient = np.array([np.pi*iOri/6.0])
#                 phase = np.pi*p/6.0
#                 crest = crest_list[contrast-1]
#                 valley = valley_list[contrast-1]
#                 generate_grating(1.0, SF, TF, orient, 16, crest, valley, video_fn, time, phase, sharpness, frameRate = 1, ecc = range_deg, buffer_ecc = buffer_deg, gtype='drifting', neye = neye, bar = False, center = center, wing = wing, mask = None, inputLMS = inputLMS,genMovie = True)
#                 # break
#                 # generate_grating(amp, spatialFrequency, temporalFrequency, direction, npixel, c1, c2, fname, time, phase, sharpness, frameRate = 120, ecc = 2.5, buffer_ecc = 0.25, gtype = 'drifting', neye = 2, bar = False, center = np.pi/2, wing = np.pi/2, mask = None, maskData = None, inputLMS = False, genMovie = True)
#                 # generate_grating(1.0, SF, TF, orient, 512, crest, valley, video_fn, time, phase, sharpness, frameRate = 120, ecc = range_deg, buffer_ecc = buffer_deg, gtype='drifting', neye = neye, bar = False, center = center, wing = wing, mask = None, inputLMS = inputLMS)    

In [12]:
# # continue random
# #固定sf和c
# center = np.pi/2
# wing = np.pi/2
# sharpness = 1
# n= 2500
# C = np.array([0.3]*n)
# P = np.random.uniform(0,360,size=n)
# SF = np.array([15.0]*n)
# D = np.random.uniform(0,180,size=n)
# C = C.astype('float32')
# P = P.astype('float32')
# SF = SF.astype('float32')
# D = D.astype('float32')
# for i in range(n):
#     video_fn = path + f'static_color-random_{i+1}'
#     c = C[i]
#     phase = P[i]
#     sf = SF[i]
#     d = D[i]
#     crest = np.array([0.5+c, 0.5-c, 0.5])#LMS
#     valley = np.array([0.5-c, 0.5+c, 0.5])
#     orient = d
    
#     cfg_fn = path + f'static_color-random_{i+1}_cfg'
#     f = open(cfg_fn+ '.bin', 'wb') # sf,d,p,c
#     np.array([sf]).astype('f4').tofile(f)
#     np.array([orient]).astype('f4').tofile(f)
#     np.array([phase]).astype('f4').tofile(f)
#     np.array([c]).astype('f4').tofile(f)
#     crest.astype('f4').tofile(f)
#     valley.astype('f4').tofile(f)
#     f.close()
    
    
#     generate_grating(1.0, sf, TF, orient, 16, crest, valley, video_fn, time, phase, sharpness, frameRate = 1, ecc = range_deg, buffer_ecc = buffer_deg, gtype='drifting', neye = neye, bar = False, center = center, wing = wing, mask = None, inputLMS = inputLMS,genMovie = True)


    
    
    
    

In [13]:
# path = '/root/autodl-tmp/ljy/resource_10/'
# # #固定c
# center = np.pi/2
# wing = np.pi/2
# sharpness = 1
# n= 5000
# C = np.array([0.3]*n)
# P = np.random.uniform(0,360,size=n)
# SF = SF = np.random.uniform(25,45,size=n)
# D = np.random.uniform(0,180,size=n)
# C = C.astype('float32')
# P = P.astype('float32')
# SF = SF.astype('float32')
# D = D.astype('float32')
# for i in range(n):
#     video_fn = path + f'static_color-random_{i+1}'
#     c = C[i]
#     phase = P[i]
#     sf = SF[i]
#     d = D[i]
#     crest = np.array([0.5+c, 0.5-c, 0.5])#LMS
#     valley = np.array([0.5-c, 0.5+c, 0.5])
#     orient = d
    
#     cfg_fn = path + f'static_color-random_{i+1}_cfg'
#     f = open(cfg_fn+ '.bin', 'wb') # sf,d,p,c
#     np.array([sf]).astype('f4').tofile(f)
#     np.array([orient]).astype('f4').tofile(f)
#     np.array([phase]).astype('f4').tofile(f)
#     np.array([c]).astype('f4').tofile(f)
#     crest.astype('f4').tofile(f)
#     valley.astype('f4').tofile(f)
#     f.close()
    
    
#     generate_grating(1.0, sf, TF, orient, 16, crest, valley, video_fn, time, phase, sharpness, frameRate = 1, ecc = range_deg, buffer_ecc = buffer_deg, gtype='drifting', neye = neye, bar = False, center = center, wing = wing, mask = None, inputLMS = inputLMS,genMovie = True)



In [14]:
# path = '/root/autodl-tmp/ljy/resource_11/'
# # path = '/root/autodl-tmp/ljy/rtest/'
# center = np.pi/2
# wing = np.pi/2
# sharpness = 1
# n = 1
# c = 0.3
# P = np.arange(0,2*np.pi,np.pi/6)
# # P = np.arange(0,1,1)
# SF = np.arange(4,44,2)
# # SF = np.arange(4,6,2)
# D = np.arange(0,np.pi,np.pi/12)
# # D = np.array([0])
# # C = C.astype('float32')
# P = P.astype('float32')
# SF = SF.astype('float32')
# D = D.astype('float32')
# crest = np.array([0.5+c, 0.5-c, 0.5])#LMS
# valley = np.array([0.5-c, 0.5+c, 0.5])
# print(D,P,SF)
# for sf in SF:
#     for orient in D:
#         for phase in P:
#             video_fn = path + f'static_color-random_{n}'
#             cfg_fn = path + f'static_color-random_{n}_cfg'
#             f = open(cfg_fn+ '.bin', 'wb') # sf,d,p,c
#             np.array([sf]).astype('f4').tofile(f)
#             np.array([orient*180/np.pi]).astype('f4').tofile(f)
#             np.array([phase*180/np.pi]).astype('f4').tofile(f)
#             np.array([c]).astype('f4').tofile(f)
#             crest.astype('f4').tofile(f)
#             valley.astype('f4').tofile(f)
#             f.close()
#             generate_grating(1.0, sf, TF, orient, 16, crest, valley, video_fn, time, phase, sharpness, frameRate = 1, ecc = range_deg, buffer_ecc = buffer_deg, gtype='drifting', neye = neye, bar = False, center = center, wing = wing, mask = None, inputLMS = inputLMS,genMovie = True)
#             n = n+1


In [15]:
# path = '/root/autodl-tmp/ljy/resource_12/'
# # path = '/root/autodl-tmp/ljy/rtest/'
# center = np.pi/2
# wing = np.pi/2
# sharpness = 1
# n = 2881
# c = 0.3
# P = np.arange(0,2*np.pi,np.pi/6)
# # P = np.arange(0,1,1)
# SF = np.arange(44,64,2)
# # SF = np.arange(4,6,2)
# D = np.arange(0,np.pi,np.pi/12)
# # D = np.array([0])
# # C = C.astype('float32')
# P = P.astype('float32')
# SF = SF.astype('float32')
# D = D.astype('float32')
# crest = np.array([0.5+c, 0.5-c, 0.5])#LMS
# valley = np.array([0.5-c, 0.5+c, 0.5])
# print(D,P,SF)
# for sf in SF:
#     for orient in D:
#         for phase in P:
#             video_fn = path + f'static_color-random_{n}'
#             cfg_fn = path + f'static_color-random_{n}_cfg'
#             f = open(cfg_fn+ '.bin', 'wb') # sf,d,p,c
#             np.array([sf]).astype('f4').tofile(f)
#             np.array([orient*180/np.pi]).astype('f4').tofile(f)
#             np.array([phase*180/np.pi]).astype('f4').tofile(f)
#             np.array([c]).astype('f4').tofile(f)
#             crest.astype('f4').tofile(f)
#             valley.astype('f4').tofile(f)
#             f.close()
#             generate_grating(1.0, sf, TF, orient, 16, crest, valley, video_fn, time, phase, sharpness, frameRate = 1, ecc = range_deg, buffer_ecc = buffer_deg, gtype='drifting', neye = neye, bar = False, center = center, wing = wing, mask = None, inputLMS = inputLMS,genMovie = True)
#             n = n+1


In [16]:
# path = '/root/autodl-tmp/ljy/resourcetest/'
# # path = '/root/autodl-tmp/ljy/rtest/'
# center = np.pi/2
# wing = np.pi/2
# sharpness = 1
# n = 1
# c = 0.3
# # P = np.arange(0,2*np.pi,np.pi/6)
# P = np.arange(0,1,1)
# # SF = np.arange(44,64,2)
# SF = np.arange(10,90,10)
# # SF = np.array([80])
# # SF = np.array([80])
# D = np.arange(0,np.pi,np.pi/12)
# # D = np.array([np.pi/18])
# # C = C.astype('float32')
# P = P.astype('float32')
# SF = SF.astype('float32')
# D = D.astype('float32')
# crest = np.array([0.5+c, 0.5-c, 0.5])#LMS
# valley = np.array([0.5-c, 0.5+c, 0.5])
# print(D,P,SF)
# for sf in SF:
#     for orient in D:
#         for phase in P:
#             video_fn = path + f'static_color-random_{n}'
#             cfg_fn = path + f'static_color-random_{n}_cfg'
#             f = open(cfg_fn+ '.bin', 'wb') # sf,d,p,c
#             np.array([sf]).astype('f4').tofile(f)
#             np.array([orient*180/np.pi]).astype('f4').tofile(f)
#             np.array([phase*180/np.pi]).astype('f4').tofile(f)
#             np.array([c]).astype('f4').tofile(f)
#             crest.astype('f4').tofile(f)
#             valley.astype('f4').tofile(f)
#             f.close()
#             generate_grating(1.0, sf, TF, orient, 16, crest, valley, video_fn, time, phase, sharpness, frameRate = 1, ecc = range_deg, buffer_ecc = buffer_deg, gtype='drifting', neye = neye, bar = False, center = center, wing = wing, mask = None, inputLMS = inputLMS,genMovie = True)
#             n = n+1


In [17]:
# path = '/root/autodl-tmp/ljy/resource_14/'
# # path = '/root/autodl-tmp/ljy/rtest/'
# center = np.pi/2
# wing = np.pi/2
# sharpness = 1
# n = 1
# c = 0.3
# # P = np.arange(0,2*np.pi,np.pi/6)
# P = np.arange(0,1,1)
# SF = np.arange(2,82,2)
# # SF = np.arange(4,6,2)
# D = np.arange(0,np.pi,np.pi/12)
# # D = np.array([0])
# # C = C.astype('float32')
# P = P.astype('float32')
# SF = SF.astype('float32')
# D = D.astype('float32')
# crest = np.array([0.5+c, 0.5-c, 0.5])#LMS
# valley = np.array([0.5-c, 0.5+c, 0.5])
# print(D,P,SF)
# for sf in SF:
#     for orient in D:
#         for phase in P:
#             video_fn = path + f'static_color-random_{n}'
#             cfg_fn = path + f'static_color-random_{n}_cfg'
#             f = open(cfg_fn+ '.bin', 'wb') # sf,d,p,c
#             np.array([sf]).astype('f4').tofile(f)
#             np.array([orient*180/np.pi]).astype('f4').tofile(f)
#             np.array([phase*180/np.pi]).astype('f4').tofile(f)
#             np.array([c]).astype('f4').tofile(f)
#             crest.astype('f4').tofile(f)
#             valley.astype('f4').tofile(f)
#             f.close()
#             generate_grating(1.0, sf, TF, orient, 16, crest, valley, video_fn, time, phase, sharpness, frameRate = 96, ecc = range_deg, buffer_ecc = buffer_deg, gtype='drifting', neye = neye, bar = False, center = center, wing = wing, mask = None, inputLMS = inputLMS,genMovie = True)
#             n = n+1


In [18]:
# path = '/root/autodl-tmp/ljy/resource_15/'
# # path = '/root/autodl-tmp/ljy/rtest/'
# center = np.pi/2
# wing = np.pi/2
# sharpness = 1
# n = 1
# c = 0.3
# # P = np.arange(0,2*np.pi,np.pi/6)
# P = np.arange(0,1,1)
# SF = np.arange(2,82,2)
# # SF = np.arange(4,6,2)
# D = np.arange(0,np.pi,np.pi/12)
# # D = np.array([0])
# # C = C.astype('float32')
# P = P.astype('float32')
# SF = SF.astype('float32')
# D = D.astype('float32')
# crest = np.array([0.5+c, 0.5-c, 0.5])#LMS
# valley = np.array([0.5-c, 0.5+c, 0.5])
# print(D,P,SF)
# for sf in SF:
#     for orient in D:
#         for phase in P:
#             video_fn = path + f'static_color-random_{n}'
#             cfg_fn = path + f'static_color-random_{n}_cfg'
#             f = open(cfg_fn+ '.bin', 'wb') # sf,d,p,c
#             np.array([sf]).astype('f4').tofile(f)
#             np.array([orient*180/np.pi]).astype('f4').tofile(f)
#             np.array([phase*180/np.pi]).astype('f4').tofile(f)
#             np.array([c]).astype('f4').tofile(f)
#             crest.astype('f4').tofile(f)
#             valley.astype('f4').tofile(f)
#             f.close()
#             generate_grating(1.0, sf, TF, orient, 32, crest, valley, video_fn, time, phase, sharpness, frameRate = 96, ecc = range_deg, buffer_ecc = buffer_deg, gtype='drifting', neye = neye, bar = False, center = center, wing = wing, mask = None, inputLMS = inputLMS,genMovie = True)
#             n = n+1


In [19]:
# path = '/root/autodl-tmp/ljy/resource_16/'
# # path = '/root/autodl-tmp/ljy/rtest/'
# center = np.pi/2
# wing = np.pi/2
# sharpness = 1
# n = 1
# c = 0.3
# # P = np.arange(0,2*np.pi,np.pi/6)
# P = np.arange(0,1,1)
# SF = np.arange(2,82,2)
# # SF = np.arange(4,6,2)
# D = np.arange(0,np.pi,np.pi/12)
# # D = np.array([0])
# # C = C.astype('float32')
# P = P.astype('float32')
# SF = SF.astype('float32')
# D = D.astype('float32')
# crest = np.array([0.5+c, 0.5-c, 0.5])#LMS
# valley = np.array([0.5-c, 0.5+c, 0.5])
# print(D,P,SF)
# for sf in SF:
#     for orient in D:
#         for phase in P:
#             video_fn = path + f'static_color-random_{n}'
#             cfg_fn = path + f'static_color-random_{n}_cfg'
#             f = open(cfg_fn+ '.bin', 'wb') # sf,d,p,c
#             np.array([sf]).astype('f4').tofile(f)
#             np.array([orient*180/np.pi]).astype('f4').tofile(f)
#             np.array([phase*180/np.pi]).astype('f4').tofile(f)
#             np.array([c]).astype('f4').tofile(f)
#             crest.astype('f4').tofile(f)
#             valley.astype('f4').tofile(f)
#             f.close()
#             generate_grating(1.0, sf, TF, orient, 64, crest, valley, video_fn, time, phase, sharpness, frameRate = 96, ecc = range_deg, buffer_ecc = buffer_deg, gtype='drifting', neye = neye, bar = False, center = center, wing = wing, mask = None, inputLMS = inputLMS,genMovie = True)
#             n = n+1


In [20]:
# path = '/root/autodl-tmp/ljy/resource_grid_benchmark_16pixel/'
# # path = '/root/autodl-tmp/ljy/rtest/'
# center = np.pi/2
# wing = np.pi/2
# sharpness = 1
# n = 1
# c = 0.3
# P = np.arange(0,2*np.pi,np.pi/6)
# # P = np.arange(0,1,1)
# SF = np.arange(4,84,4)
# # SF = np.arange(4,6,2)
# D = np.arange(0,np.pi,np.pi/12)
# # D = np.array([0])
# # C = C.astype('float32')
# P = P.astype('float32')
# SF = SF.astype('float32')
# D = D.astype('float32')
# crest = np.array([0.5+c, 0.5-c, 0.5])#LMS
# valley = np.array([0.5-c, 0.5+c, 0.5])
# print(D,P,SF)
# for sf in SF:
#     for orient in D:
#         for phase in P:
#             video_fn = path + f'static_color-grid_{n}'
#             cfg_fn = path + f'static_color-grid_{n}_cfg'
#             f = open(cfg_fn+ '.bin', 'wb') # sf,d,p,c
#             np.array([sf]).astype('f4').tofile(f)
#             np.array([orient*180/np.pi]).astype('f4').tofile(f)
#             np.array([phase*180/np.pi]).astype('f4').tofile(f)
#             np.array([c]).astype('f4').tofile(f)
#             crest.astype('f4').tofile(f)
#             valley.astype('f4').tofile(f)
#             f.close()
#             generate_grating(1.0, sf, TF, orient, 16, crest, valley, video_fn, time, phase, sharpness, frameRate = 1, ecc = range_deg, buffer_ecc = buffer_deg, gtype='drifting', neye = neye, bar = False, center = center, wing = wing, mask = None, inputLMS = inputLMS,genMovie = True)
#             n = n+1


In [21]:
# path = '/root/autodl-tmp/ljy/resource_grid_benchmark_32pixel/'
# # path = '/root/autodl-tmp/ljy/rtest/'
# center = np.pi/2
# wing = np.pi/2
# sharpness = 1
# n = 1
# c = 0.3
# P = np.arange(0,2*np.pi,np.pi/6)
# # P = np.arange(0,1,1)
# SF = np.arange(4,84,4)
# # SF = np.arange(4,6,2)
# D = np.arange(0,np.pi,np.pi/12)
# # D = np.array([0])
# # C = C.astype('float32')
# P = P.astype('float32')
# SF = SF.astype('float32')
# D = D.astype('float32')
# crest = np.array([0.5+c, 0.5-c, 0.5])#LMS
# valley = np.array([0.5-c, 0.5+c, 0.5])
# print(D,P,SF)
# for sf in SF:
#     for orient in D:
#         for phase in P:
#             video_fn = path + f'static_color-grid_{n}'
#             cfg_fn = path + f'static_color-grid_{n}_cfg'
#             f = open(cfg_fn+ '.bin', 'wb') # sf,d,p,c
#             np.array([sf]).astype('f4').tofile(f)
#             np.array([orient*180/np.pi]).astype('f4').tofile(f)
#             np.array([phase*180/np.pi]).astype('f4').tofile(f)
#             np.array([c]).astype('f4').tofile(f)
#             crest.astype('f4').tofile(f)
#             valley.astype('f4').tofile(f)
#             f.close()
#             generate_grating(1.0, sf, TF, orient, 32, crest, valley, video_fn, time, phase, sharpness, frameRate = 1, ecc = range_deg, buffer_ecc = buffer_deg, gtype='drifting', neye = neye, bar = False, center = center, wing = wing, mask = None, inputLMS = inputLMS,genMovie = True)
#             n = n+1


In [22]:
# path = '/root/autodl-tmp/ljy/resource_grid_benchmark_64pixel/'
# # path = '/root/autodl-tmp/ljy/rtest/'
# center = np.pi/2
# wing = np.pi/2
# sharpness = 1
# n = 1
# c = 0.3
# P = np.arange(0,2*np.pi,np.pi/6)
# # P = np.arange(0,1,1)
# SF = np.arange(4,84,4)
# # SF = np.arange(4,6,2)
# D = np.arange(0,np.pi,np.pi/12)
# # D = np.array([0])
# # C = C.astype('float32')
# P = P.astype('float32')
# SF = SF.astype('float32')
# D = D.astype('float32')
# crest = np.array([0.5+c, 0.5-c, 0.5])#LMS
# valley = np.array([0.5-c, 0.5+c, 0.5])
# print(D,P,SF)
# for sf in SF:
#     for orient in D:
#         for phase in P:
#             video_fn = path + f'static_color-grid_{n}'
#             cfg_fn = path + f'static_color-grid_{n}_cfg'
#             f = open(cfg_fn+ '.bin', 'wb') # sf,d,p,c
#             np.array([sf]).astype('f4').tofile(f)
#             np.array([orient*180/np.pi]).astype('f4').tofile(f)
#             np.array([phase*180/np.pi]).astype('f4').tofile(f)
#             np.array([c]).astype('f4').tofile(f)
#             crest.astype('f4').tofile(f)
#             valley.astype('f4').tofile(f)
#             f.close()
#             generate_grating(1.0, sf, TF, orient, 64, crest, valley, video_fn, time, phase, sharpness, frameRate = 1, ecc = range_deg, buffer_ecc = buffer_deg, gtype='drifting', neye = neye, bar = False, center = center, wing = wing, mask = None, inputLMS = inputLMS,genMovie = True)
#             n = n+1


In [23]:
# path = '/root/autodl-tmp/ljy/resource_random_valid/'
# # path = '/root/autodl-tmp/ljy/rtest/'
# center = np.pi/2
# wing = np.pi/2
# sharpness = 1
# n = 400
# c = 0.3
# P = np.random.uniform(0,2*np.pi,size=n)
# SF = np.random.uniform(4,62,size=n)
# D = np.random.uniform(0,np.pi,size=n)
# P = P.astype('float32')
# SF = SF.astype('float32')
# D = D.astype('float32')
# crest = np.array([0.5+c, 0.5-c, 0.5])#LMS
# valley = np.array([0.5-c, 0.5+c, 0.5])
# print(D*180/np.pi,SF)
# for i in range(n):
#     sf = SF[i]
#     orient = D[i]
#     phase = P[i]

#     video_fn = path + f'static_color-random_{i+1}'
#     cfg_fn = path + f'static_color-random_{i+1}_cfg'
#     f = open(cfg_fn+ '.bin', 'wb') # sf,d,p,c
#     np.array([sf]).astype('f4').tofile(f)
#     np.array([orient*180/np.pi]).astype('f4').tofile(f)
#     np.array([phase*180/np.pi]).astype('f4').tofile(f)
#     np.array([c]).astype('f4').tofile(f)
#     crest.astype('f4').tofile(f)
#     valley.astype('f4').tofile(f)
#     f.close()
#     generate_grating(1.0, sf, TF, orient, 16, crest, valley, video_fn, time, phase, sharpness, frameRate = 1, ecc = range_deg, buffer_ecc = buffer_deg, gtype='drifting', neye = neye, bar = False, center = center, wing = wing, mask = None, inputLMS = inputLMS,genMovie = True)



# 

In [24]:
# path = '/root/autodl-tmp/ljy/resource_onlyLGN_sf50/'
# # path = '/root/autodl-tmp/ljy/rtest/'
# center = np.pi/2
# wing = np.pi/2
# sharpness = 1
# n = 1
# c = 0.3
# # P = np.arange(0,2*np.pi,np.pi/6)
# P = np.arange(0,1,1)
# # SF = np.arange(4,84,4)
# SF = np.arange(50,52,2)
# D = np.arange(0,np.pi,np.pi/12)
# # D = np.array([0])
# # C = C.astype('float32')
# P = P.astype('float32')
# SF = SF.astype('float32')
# D = D.astype('float32')
# crest = np.array([0.5+c, 0.5-c, 0.5])#LMS
# valley = np.array([0.5-c, 0.5+c, 0.5])
# print(D,P,SF)
# for sf in SF:
#     for orient in D:
#         for phase in P:
#             video_fn = path + f'static_color-grid_{n}'
#             cfg_fn = path + f'static_color-grid_{n}_cfg'
#             f = open(cfg_fn+ '.bin', 'wb') # sf,d,p,c
#             np.array([sf]).astype('f4').tofile(f)
#             np.array([orient*180/np.pi]).astype('f4').tofile(f)
#             np.array([phase*180/np.pi]).astype('f4').tofile(f)
#             np.array([c]).astype('f4').tofile(f)
#             crest.astype('f4').tofile(f)
#             valley.astype('f4').tofile(f)
#             f.close()
#             generate_grating(1.0, sf, TF, orient, 32, crest, valley, video_fn, time, phase, sharpness, frameRate = 96, ecc = range_deg, buffer_ecc = buffer_deg, gtype='drifting', neye = neye, bar = False, center = center, wing = wing, mask = None, inputLMS = inputLMS,genMovie = True)
#             n = n+1


In [25]:
def acuity(ecc):
    k = 0.2049795945022049
    log_cpd0 = 3.6741080244555278
    cpd = np.exp(-k*ecc + log_cpd0)
    return 2/cpd/4

acuity(0.08)
K_onC = 29.13289963
K_onS = 23.17378917
K_offC = 22.71914498
K_offS = 12.53276353
r_C = (acuity(0.095) + acuity(0))/2
#r_C = 0.0065
r_S = r_C*3
cov = 0.53753
def zeroCross(k1, k2, r1, r2):
    return np.sqrt(np.log(k1/k2)/(r2*r2 - r1*r1))*r1*r2
SF = 1.0/(zeroCross(K_offC, K_onS*cov, r_C, r_S)*2 + zeroCross(K_onC, K_offS*cov, r_C, r_S)*2)
print(SF)

inputLMS = True

#range_deg = 0.095 # eccentricity from the origin
range_deg = 0.0344#0.12672379774682216 # eccentricity from the origin
print(acuity(range_deg))
# buffer_deg = acuity(range_deg)*2
buffer_deg = acuity(range_deg)*4
print(f'range_deg = {range_deg}, buffer_deg = {buffer_deg}')
SF = 20
# SF = 10
TF = 8
time = np.array([1/TF])
neye = 1
#path = 'D:/scratch/patchV1/resource/'
#path = 'C:/Users/gueux/Repos/patchV1/Data/'
path = '/root/autodl-tmp/ljy/resource_8/'

18.53509145317477
0.012775782312929865
range_deg = 0.0344, buffer_deg = 0.05110312925171946


In [26]:

# path = '/root/autodl-tmp/ljy/resource_onlyLGN_sf20_new/'
# # path = '/root/autodl-tmp/ljy/rtest/'
# center = np.pi/2
# wing = np.pi/2
# sharpness = 1
# n = 1
# c = 0.3
# # P = np.arange(0,2*np.pi,np.pi/6)
# P = np.arange(0,1,1)
# # SF = np.arange(4,84,4)
# SF = np.arange(20,22,2)
# D = np.arange(0,np.pi,np.pi/12)
# # D = np.array([0])
# # C = C.astype('float32')
# P = P.astype('float32')
# SF = SF.astype('float32')
# D = D.astype('float32')
# crest = np.array([0.5+c, 0.5-c, 0.5])#LMS
# valley = np.array([0.5-c, 0.5+c, 0.5])
# print(D,P,SF)
# for sf in SF:
#     for orient in D:
#         for phase in P:
#             video_fn = path + f'static_color-grid_{n}'
#             cfg_fn = path + f'static_color-grid_{n}_cfg'
#             f = open(cfg_fn+ '.bin', 'wb') # sf,d,p,c
#             np.array([sf]).astype('f4').tofile(f)
#             np.array([orient*180/np.pi]).astype('f4').tofile(f)
#             np.array([phase*180/np.pi]).astype('f4').tofile(f)
#             np.array([c]).astype('f4').tofile(f)
#             crest.astype('f4').tofile(f)
#             valley.astype('f4').tofile(f)
#             f.close()
#             generate_grating(1.0, sf, TF, orient,256 , crest, valley, video_fn, time, phase, sharpness, frameRate = 96, ecc = range_deg, buffer_ecc = buffer_deg, gtype='drifting', neye = neye, bar = False, center = center, wing = wing, mask = None, inputLMS = inputLMS,genMovie = True)
#             n = n+1


In [27]:

# path = '/root/autodl-tmp/ljy/uniform_sample/'
# # path = '/root/autodl-tmp/ljy/rtest/'
# center = np.pi/2
# wing = np.pi/2
# sharpness = 1
# n = 1
# c = 0.3
# # P = np.arange(0,2*np.pi,np.pi/6)
# P = np.arange(0,1,1)
# # SF = np.arange(4,84,4)
# SF = np.arange(40,42,2)
# D = np.arange(0,np.pi,np.pi/12)
# # D = np.array([0])
# # C = C.astype('float32')
# P = P.astype('float32')
# SF = SF.astype('float32')
# D = D.astype('float32')
# crest = np.array([0.5+c, 0.5-c, 0.5])#LMS
# valley = np.array([0.5-c, 0.5+c, 0.5])
# print(D,P,SF)
# for sf in SF:
#     for orient in D:
#         for phase in P:
#             video_fn = path + f'static_color-grid_{n}'
#             cfg_fn = path + f'static_color-grid_{n}_cfg'
#             f = open(cfg_fn+ '.bin', 'wb') # sf,d,p,c
#             np.array([sf]).astype('f4').tofile(f)
#             np.array([orient*180/np.pi]).astype('f4').tofile(f)
#             np.array([phase*180/np.pi]).astype('f4').tofile(f)
#             np.array([c]).astype('f4').tofile(f)
#             crest.astype('f4').tofile(f)
#             valley.astype('f4').tofile(f)
#             f.close()
#             generate_grating(1.0, sf, TF, orient,1024, crest, valley, video_fn, time, phase, sharpness, frameRate = 1, ecc = range_deg, buffer_ecc = buffer_deg, gtype='drifting', neye = neye, bar = False, center = center, wing = wing, mask = None, inputLMS = inputLMS,genMovie = True)
#             n = n+1


In [28]:

# path = '/root/autodl-tmp/ljy/resource_static_32pixel/'
# # path = '/root/autodl-tmp/ljy/rtest/'
# center = np.pi/2
# wing = np.pi/2
# sharpness = 1
# n = 1
# c = 0.3
# P = np.arange(0,2*np.pi,np.pi/6)
# # P = np.arange(0,1,1)
# # SF = np.arange(4,84,4)
# SF = np.arange(4,64,4)
# D = np.arange(0,np.pi,np.pi/12)
# # D = np.array([0])
# # C = C.astype('float32')
# P = P.astype('float32')
# SF = SF.astype('float32')
# D = D.astype('float32')
# crest = np.array([0.5+c, 0.5-c, 0.5])#LMS
# valley = np.array([0.5-c, 0.5+c, 0.5])
# print(D,P,SF)
# for sf in SF:
#     for orient in D:
#         for phase in P:
#             video_fn = path + f'static_color-grid_{n}'
#             cfg_fn = path + f'static_color-grid_{n}_cfg'
#             f = open(cfg_fn+ '.bin', 'wb') # sf,d,p,c
#             np.array([sf]).astype('f4').tofile(f)
#             np.array([orient*180/np.pi]).astype('f4').tofile(f)
#             np.array([phase*180/np.pi]).astype('f4').tofile(f)
#             np.array([c]).astype('f4').tofile(f)
#             crest.astype('f4').tofile(f)
#             valley.astype('f4').tofile(f)
#             f.close()
#             generate_grating(1.0, sf, TF, orient,32, crest, valley, video_fn, time, phase, sharpness, frameRate = 1, ecc = range_deg, buffer_ecc = buffer_deg, gtype='drifting', neye = neye, bar = False, center = center, wing = wing, mask = None, inputLMS = inputLMS,genMovie = True)
#             n = n+1


In [29]:

# path = '/root/autodl-tmp/ljy/resource_drifting_32pixel/'
# center = np.pi/2
# wing = np.pi/2
# sharpness = 1
# n = 1
# c = 0.3
# # P = np.arange(0,2*np.pi,np.pi/6)
# P = np.arange(0,1,1)
# SF = np.arange(10,70,10)
# # SF = np.arange(4,64,4)
# # D = np.arange(0,np.pi,np.pi/12)
# D = np.arange(0,np.pi,np.pi/6)
# # D = np.array([0])
# # C = C.astype('float32')
# P = P.astype('float32')
# SF = SF.astype('float32')
# D = D.astype('float32')
# crest = np.array([0.5+c, 0.5-c, 0.5])#LMS
# valley = np.array([0.5-c, 0.5+c, 0.5])
# print(D,P,SF)
# for sf in SF:
#     for orient in D:
#         for phase in P:
#             video_fn = path + f'drifting_color-grid_{n}'
#             cfg_fn = path + f'drifting_color-grid_{n}_cfg'
#             f = open(cfg_fn+ '.bin', 'wb') # sf,d,p,c
#             np.array([sf]).astype('f4').tofile(f)
#             np.array([orient*180/np.pi]).astype('f4').tofile(f)
#             np.array([phase*180/np.pi]).astype('f4').tofile(f)
#             np.array([c]).astype('f4').tofile(f)
#             crest.astype('f4').tofile(f)
#             valley.astype('f4').tofile(f)
#             f.close()
#             generate_grating(1.0, sf, TF, orient,32, crest, valley, video_fn, time, phase, sharpness, frameRate = 96, ecc = range_deg, buffer_ecc = buffer_deg, gtype='drifting', neye = neye, bar = False, center = center, wing = wing, mask = None, inputLMS = inputLMS,genMovie = True)
#             n = n+1


In [30]:

# path = '/root/autodl-tmp/ljy/resource_drifting_32pixel/'
# center = np.pi/2
# wing = np.pi/2
# sharpness = 1
# n = 1
# c = 0.3
# # P = np.arange(0,2*np.pi,np.pi/6)
# P = np.arange(0,1,1)
# SF = np.arange(20,30,10)
# # SF = np.arange(4,64,4)
# # D = np.arange(0,np.pi,np.pi/12)
# D = np.arange(0,np.pi,np.pi/6)
# # D = np.array([0])
# # C = C.astype('float32')
# P = P.astype('float32')
# SF = SF.astype('float32')
# D = D.astype('float32')
# crest = np.array([0.5+c, 0.5-c, 0.5])#LMS
# valley = np.array([0.5-c, 0.5+c, 0.5])
# print(D,P,SF)
# for sf in SF:
#     for orient in D:
#         for phase in P:
#             video_fn = path + f'drifting_color_{n}'
#             cfg_fn = path + f'drifting_color_{n}_cfg'
#             f = open(cfg_fn+ '.bin', 'wb') # sf,d,p,c
#             np.array([sf]).astype('f4').tofile(f)
#             np.array([orient*180/np.pi]).astype('f4').tofile(f)
#             np.array([phase*180/np.pi]).astype('f4').tofile(f)
#             np.array([c]).astype('f4').tofile(f)
#             crest.astype('f4').tofile(f)
#             valley.astype('f4').tofile(f)
#             f.close()
#             generate_grating(1.0, sf, TF, orient,32, crest, valley, video_fn, time, phase, sharpness, frameRate = 96, ecc = range_deg, buffer_ecc = buffer_deg, gtype='drifting', neye = neye, bar = False, center = center, wing = wing, mask = None, inputLMS = inputLMS,genMovie = True)
#             n = n+1


In [31]:

# path = '/root/autodl-tmp/ljy/resource_repeat/'
# center = np.pi/2
# wing = np.pi/2
# sharpness = 1
# n = 1
# C = np.arange(0.1, 0.6, 0.1)
# # P = np.arange(0,2*np.pi,np.pi/6)
# P = np.arange(0,1,1)
# SF = np.arange(24,30,10)
# # SF = np.arange(4,64,4)
# # D = np.arange(0,np.pi,np.pi/12)
# D = np.arange(0,np.pi,np.pi/6)
# # D = np.array([0])
# # C = C.astype('float32')
# P = P.astype('float32')
# SF = SF.astype('float32')
# D = D.astype('float32')
# C = C.astype('float32')
# for c in C:
#     for sf in SF:
#         for orient in D:
#             for phase in P:
#                 crest = np.array([0.5+c, 0.5-c, 0.5])#LMS
#                 valley = np.array([0.5-c, 0.5+c, 0.5])
#                 video_fn = path + f'drifting_color_{n}'
#                 cfg_fn = path + f'drifting_color_{n}_cfg'
#                 f = open(cfg_fn+ '.bin', 'wb') # sf,d,p,c
#                 np.array([sf]).astype('f4').tofile(f)
#                 np.array([orient*180/np.pi]).astype('f4').tofile(f)
#                 np.array([phase*180/np.pi]).astype('f4').tofile(f)
#                 np.array([c]).astype('f4').tofile(f)
#                 crest.astype('f4').tofile(f)
#                 valley.astype('f4').tofile(f)
#                 f.close()
#                 generate_grating(1.0, sf, TF, orient,32, crest, valley, video_fn, time, phase, sharpness, frameRate = 96, ecc = range_deg, buffer_ecc = buffer_deg, gtype='drifting', neye = neye, bar = False, center = center, wing = wing, mask = None, inputLMS = inputLMS,genMovie = True)
#                 n = n+1


In [35]:

path = '/root/autodl-tmp/ljy/resource_repeat/'
center = np.pi/2
wing = np.pi/2
sharpness = 1
n = 1
C = np.arange(0.0, 0.6, 0.1)
# P = np.arange(0,2*np.pi,np.pi/6)
P = np.arange(0,1,1)
SF = np.arange(24,30,10)
# SF = np.arange(4,64,4)
# D = np.arange(0,np.pi,np.pi/12)
# D = np.arange(0,np.pi,np.pi/6)
D = np.array([0])
# C = C.astype('float32')
P = P.astype('float32')
SF = SF.astype('float32')
D = D.astype('float32')
C = C.astype('float32')
for c in C:
    for sf in SF:
        for orient in D:
            for phase in P:
                crest = np.array([0.5+c, 0.5-c, 0.5])#LMS
                valley = np.array([0.5-c, 0.5+c, 0.5])
                video_fn = path + f'drifting_color_{n}'
                cfg_fn = path + f'drifting_color_{n}_cfg'
                f = open(cfg_fn+ '.bin', 'wb') # sf,d,p,c
                np.array([sf]).astype('f4').tofile(f)
                np.array([orient*180/np.pi]).astype('f4').tofile(f)
                np.array([phase*180/np.pi]).astype('f4').tofile(f)
                np.array([c]).astype('f4').tofile(f)
                crest.astype('f4').tofile(f)
                valley.astype('f4').tofile(f)
                f.close()
                generate_grating(1.0, sf, TF, orient,32, crest, valley, video_fn, time, phase, sharpness, frameRate = 96, ecc = range_deg, buffer_ecc = buffer_deg, gtype='drifting', neye = neye, bar = False, center = center, wing = wing, mask = None, inputLMS = inputLMS,genMovie = True)
                n = n+1


32 degree per pixel
crest in sRGB: [0.7992093  0.71806023 0.70442258]
valley in sRGB: [0.7992093  0.71806023 0.70442258]
0.005343945578232466 degree per pixel
ecc = 0.0344, buffer_ecc = 0.05110312925171946
12
exact 12 frames in total
sharpness=1.0
it: 0
it: 1
it: 2
it: 3
it: 4
it: 5
it: 6
it: 7
it: 8
it: 9
it: 10
it: 11
32 degree per pixel
crest in sRGB: [1.02220551 0.61576424 0.70970734]
valley in sRGB: [0.42848606 0.80422963 0.69908582]
0.005343945578232466 degree per pixel
ecc = 0.0344, buffer_ecc = 0.05110312925171946
12
exact 12 frames in total
sharpness=1.0
it: 0
sRGB space is not enough to represent the color
(array([0.42917775, 0.61589776, 0.69909214]), array([1.02197991, 0.80413521, 0.70970115]))
it: 1
sRGB space is not enough to represent the color
(array([0.42855035, 0.61741567, 0.69908641]), array([1.01940614, 0.80422087, 0.70963064]))
it: 2
sRGB space is not enough to represent the color
(array([0.43027435, 0.61578461, 0.69910217]), array([1.02217109, 0.80398509, 0.7097064